version: "3"

services:
  ares_mail:
    build:
      context: ./ares-mail
      dockerfile: ./Dockerfile
    container_name: ares_mail
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASS=postgres_2022
      - PG_PORT=5432
      - MAIL_HOST=smtp.ym.163.com
      - MAIL_SMTP_PORT=994
      - MAIL_SMTP_SECURE=true
      - MAIL_AUTH_USER=xx@xx.com
      - MAIL_AUTH_PASS=xxxx
      - MAIL_TO=xxx@qq.com
    image: aresprotocollab/ares_mail
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  ares_substrate_tools:
    build:
      context: https://github.com/kami1983/ares-chain-fornt-end.git#v1.0.4
      dockerfile: ./Dockerfile
    container_name: ares_substrate_tools_odyssey
    image: aresprotocollab/ares_substrate_tools
    ports:
      - "6780:80"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
  postgres:
    image: postgres:12-alpine
    ports:
      - 5445:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_2022
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Update subquery.
  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres_2022
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3101:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres_2022
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000