specVersion: 0.2.0
name: hello-ares
version: 0.0.4
description: This SubQuery project can be use as a st...
repository:
schema:
  file: ./schema.graphql
network:
  endpoint: wss://gladios.aresprotocol.io
  genesisHash: '0xa8a43b9e46db3280e956efd95c3fb2bac8919d62f01a0cf0054cf3cbdce9130b'
#  endpoint: ws://127.0.0.1:9949
#  endpoint: ws://192.168.50.220:9949
#  endpoint: ws://202.182.100.187:7644
#  genesisHash: '0xd18bcb44da1badfcf73959152106967346cdaaf7ef6aae8d3abe3a751174a5ae'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
#    startBlock: 78000
    # 这个区块是 2022-06-10 0点之前的区块
#    startBlock: 433151
#    startBlock: 477200
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
#        - handler: handleBlock
#          kind: substrate/BlockHandler
#        - handler: handleCall
#          kind: substrate/CallHandler
        - handler: handleEventAresOraclePurchasedAvgPrice
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: PurchasedAvgPrice
        - handler: handleEventAresOracleNewPurchasedRequest
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPurchasedRequest
        - handler: handleEventAresOracleNewPreCheckTask
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPreCheckTask
        - handler: handleEventAresOracleNewPreCheckResult
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPreCheckResult
        - handler: handleEventPurchaseRewardToken
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: PurchaseRewardToken
        - handler: handleEventEndOfAskEra
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: EndOfAskEra
        - handler: handleEventInsufficientCountOfValidators
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: InsufficientCountOfValidators
        - handler: handleEventPayForPurchase
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: PayForPurchase
        - handler: handleEventStakingBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleEventStakingChilled
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Chilled
        - handler: handleEventImOnlineSomeOffline
          kind: substrate/EventHandler
          filter:
            module: imOnline
            method: SomeOffline
        - handler: handleEventSessionNewSession
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleEventStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
