specVersion: 0.2.0
name: hello-ares
version: 0.0.4
description: This SubQuery project can be use as a st...
repository:
schema:
  file: ./schema.graphql
network:
#  endpoint: wss://gladios.aresprotocol.io
#  genesisHash: '0xa8a43b9e46db3280e956efd95c3fb2bac8919d62f01a0cf0054cf3cbdce9130b'
#  endpoint: ws://192.168.50.44:9944
#  genesisHash: '0xb8f3755a5250d66e20316f04a7b0981735202f758abafc46fbf1ec19a397d2b0'
#  endpoint: ws://202.182.100.187:19944
#  genesisHash: '0x9ed76c03eb5c876f98df99154b2df716646ba475d4bdf66551c919c346724cc4'
  endpoint: ws://202.182.100.187:7644
  genesisHash: '0xb8bafa2977b149453373c45481f0a3a871b6bc5719d753b3a1403b4d74c14ef2'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
#        - handler: handleBlock
#          kind: substrate/BlockHandler
#        - handler: handleCall
#          kind: substrate/CallHandler
        - handler: handleEventAresOraclePurchasedAvgPrice
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: PurchasedAvgPrice
        - handler: handleEventAresOracleNewPurchasedRequest
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPurchasedRequest
        - handler: handleEventAresOracleNewPreCheckTask
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPreCheckTask
        - handler: handleEventAresOracleNewPreCheckResult
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: NewPreCheckResult
        - handler: handleEventPurchaseRewardToken
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: PurchaseRewardToken
        - handler: handleEventEndOfAskEra
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: EndOfAskEra
        - handler: handleEventInsufficientCountOfValidators
          kind: substrate/EventHandler
          filter:
            module: aresOracle
            method: InsufficientCountOfValidators
        - handler: handleEventPayForPurchase
          kind: substrate/EventHandler
          filter:
            module: oracleFinance
            method: PayForPurchase
        - handler: handleEventStakingBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleEventStakingChilled
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Chilled
        - handler: handleEventImOnlineSomeOffline
          kind: substrate/EventHandler
          filter:
            module: imOnline
            method: SomeOffline
        - handler: handleEventSessionNewSession
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleEventStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleCrossChainRequestEvent
          kind: substrate/EventHandler
          filter:
            module: manualBridge
            method: CrossChainRequest
        - handler: handleManualBridgeCompletedListEvent
          kind: substrate/EventHandler
          filter:
            module: manualBridge
            method: CompletedList
